import type { Subscription } from './types';

export const SUBSCRIPTIONS: Subscription[] = [
  // ── Chat AI Assistants ──────────────────────────────────────────────────────
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    provider: 'OpenAI',
    providerId: 'openai',
    description: 'The world\'s most popular AI assistant with GPT-4o, web search, DALL·E, and Sora video.',
    category: 'chat',
    url: 'https://openai.com/chatgpt/pricing',
    underlyingModels: ['openai/gpt-4o', 'openai/o3'],
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['GPT-4o (limited)', 'Web search (limited)', 'DALL·E 3 (limited)', 'GPT-4o mini (unlimited)'],
        highlight: false,
      },
      {
        name: 'Plus',
        monthlyPrice: 20,
        annualMonthlyPrice: 20,
        perSeat: false,
        features: ['GPT-5 with advanced reasoning', 'Expanded deep research & agent mode', 'DALL·E + image generation', 'Sora video (limited)', 'Memory & Projects', 'Custom GPTs'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Pro',
        monthlyPrice: 200,
        annualMonthlyPrice: 200,
        perSeat: false,
        features: ['Unlimited GPT-5 & o1 Pro mode', 'o3 with extended compute', 'Advanced Voice mode', 'Sora video generation', 'Front-of-line for all new features', 'Codex agent'],
        highlight: false,
        badge: 'Max Power',
      },
      {
        name: 'Team',
        monthlyPrice: 30,
        annualMonthlyPrice: 25,
        perSeat: true,
        features: ['Everything in Plus', 'Shared workspace & Projects', 'Admin console', 'Higher GPT-5 message caps', 'Data not used for training'],
        highlight: false,
      },
      {
        name: 'Enterprise',
        monthlyPrice: null,
        annualMonthlyPrice: null,
        perSeat: true,
        features: ['Unlimited GPT-5', 'SOC 2 & SSO', 'Analytics dashboards', 'Custom data retention', '24/7 priority support'],
        highlight: false,
        badge: 'Contact Sales',
      },
    ],
  },
  {
    id: 'claude-ai',
    name: 'Claude.ai',
    provider: 'Anthropic',
    providerId: 'anthropic',
    description: 'Anthropic\'s AI assistant with long context, coding, research, and extended thinking.',
    category: 'chat',
    url: 'https://claude.ai/pricing',
    underlyingModels: ['anthropic/claude-opus-4', 'anthropic/claude-sonnet-4-5'],
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Claude Sonnet (limited)', 'Basic Projects', '10–25 messages per 5-hr window'],
        highlight: false,
      },
      {
        name: 'Pro',
        monthlyPrice: 20,
        annualMonthlyPrice: 17,
        perSeat: false,
        features: ['~45 prompts / 5-hr window', 'All Claude models incl. Opus', 'Web search & file analysis', 'Projects & Artifacts', 'Priority access'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Max 5×',
        monthlyPrice: 100,
        annualMonthlyPrice: 100,
        perSeat: false,
        features: ['5× Pro usage limits', 'Claude Code (terminal agent)', 'Cowork multi-step delegation', 'Priority routing at peak', 'Early access to new models'],
        highlight: false,
      },
      {
        name: 'Max 20×',
        monthlyPrice: 200,
        annualMonthlyPrice: 200,
        perSeat: false,
        features: ['20× Pro usage limits', 'Maximum priority routing', 'Effectively no daily limits', 'Claude Code included', 'All Max 5× features'],
        highlight: false,
        badge: 'Power Users',
      },
      {
        name: 'Team',
        monthlyPrice: 30,
        annualMonthlyPrice: 25,
        perSeat: true,
        features: ['Pro-level usage per seat', 'SSO & admin controls', 'Shared projects', 'Slack & M365 integration', 'No training on team data'],
        highlight: false,
      },
      {
        name: 'Enterprise',
        monthlyPrice: null,
        annualMonthlyPrice: null,
        perSeat: true,
        features: ['SCIM provisioning & audit logs', '400K+ token context', 'Advanced compliance', 'Dedicated support', 'Team Premium: Max-level usage/seat'],
        highlight: false,
        badge: 'Contact Sales',
      },
    ],
  },
  {
    id: 'gemini',
    name: 'Google AI',
    provider: 'Google',
    providerId: 'google',
    description: 'Google\'s AI suite — Gemini models, Deep Research, NotebookLM, and Veo video generation.',
    category: 'chat',
    url: 'https://gemini.google/subscriptions/',
    underlyingModels: ['google/gemini-2.5-pro-preview'],
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Gemini 2.5 Flash', 'Basic Deep Research', 'Google integrations', 'Limited Audio Overviews'],
        highlight: false,
      },
      {
        name: 'AI Plus',
        monthlyPrice: 7.99,
        annualMonthlyPrice: 7.99,
        perSeat: false,
        features: ['Gemini 3 Pro access', 'Veo 3.1 Fast video creation', '200 monthly AI credits', '200 GB storage', 'Family sharing (up to 5)'],
        highlight: false,
      },
      {
        name: 'AI Pro',
        monthlyPrice: 19.99,
        annualMonthlyPrice: 19.99,
        perSeat: false,
        features: ['1M token context window', '100 Deep Research reports/day', 'NotebookLM Pro', '2 TB storage', 'Gemini Code Assist', '5× Jules coding agent limits'],
        highlight: true,
        badge: 'Best Value',
      },
      {
        name: 'AI Ultra',
        monthlyPrice: 249.99,
        annualMonthlyPrice: 249.99,
        perSeat: false,
        features: ['500 Gemini prompts/day', '200 Deep Research reports/day', 'Deep Think reasoning (192K ctx)', 'Veo 3 with audio generation', 'Project Mariner agentic browsing', '30 TB storage', 'YouTube Premium included'],
        highlight: false,
        badge: 'Max Power',
      },
    ],
  },
  {
    id: 'grok',
    name: 'Grok',
    provider: 'xAI',
    providerId: 'x-ai',
    description: 'xAI\'s AI with real-time X data, deep search, Think mode, and SuperGrok Heavy.',
    category: 'chat',
    url: 'https://x.ai/pricing',
    underlyingModels: ['x-ai/grok-3', 'x-ai/grok-3-mini'],
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Grok 4 (limited)', 'Basic Aurora image gen', 'grok.com access'],
        highlight: false,
      },
      {
        name: 'X Premium',
        monthlyPrice: 8,
        annualMonthlyPrice: 8,
        perSeat: false,
        features: ['Basic Grok access within X', 'Blue checkmark', 'Ad revenue sharing'],
        highlight: false,
      },
      {
        name: 'X Premium+',
        monthlyPrice: 40,
        annualMonthlyPrice: 40,
        perSeat: false,
        features: ['Priority Grok access within X', 'Ad-free X browsing', 'Full X social features'],
        highlight: false,
      },
      {
        name: 'SuperGrok',
        monthlyPrice: 30,
        annualMonthlyPrice: 25,
        perSeat: false,
        features: ['Grok 4 & Grok 3 access', '128K token memory', 'Deep Search', 'Think mode', 'Premium Imagine image model', 'Companions API'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'SuperGrok Heavy',
        monthlyPrice: 300,
        annualMonthlyPrice: 300,
        perSeat: false,
        features: ['Grok 4 Heavy (highest compute)', '428K token memory', 'Maximum consumer-level AI', 'Early access to all new features', 'Priority voice'],
        highlight: false,
        badge: 'Max Power',
      },
    ],
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    provider: 'Perplexity',
    providerId: 'perplexityai',
    description: 'AI-powered answer engine with real-time web search, citations, and Labs creative tools.',
    category: 'search',
    url: 'https://perplexity.ai/pro',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['5 Pro searches/day', 'Unlimited standard searches', 'Web citations', 'Basic file uploads'],
        highlight: false,
      },
      {
        name: 'Pro',
        monthlyPrice: 20,
        annualMonthlyPrice: 16.67,
        perSeat: false,
        features: ['300+ Pro searches/day', 'GPT-4o, Claude 3.5 & more', 'Unlimited file uploads', 'Image generation', '$5/mo API credits', 'Standard Labs access'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Max',
        monthlyPrice: 200,
        annualMonthlyPrice: 166.67,
        perSeat: false,
        features: ['Unlimited Labs (dashboards, apps, spreadsheets)', 'Frontier models (o3-pro, Claude Opus 4)', 'Comet browser + Max Assistant early access', '10,000 Computer credits/mo', 'Sora 2 Pro video generation', 'Priority support'],
        highlight: false,
        badge: 'Power Users',
      },
      {
        name: 'Enterprise Pro',
        monthlyPrice: 40,
        annualMonthlyPrice: 40,
        perSeat: true,
        features: ['Everything in Pro', 'Team dashboard', 'Centralized billing', 'SOC 2 compliance', 'Data never used for training'],
        highlight: false,
      },
      {
        name: 'Enterprise Max',
        monthlyPrice: 325,
        annualMonthlyPrice: 270.83,
        perSeat: true,
        features: ['Everything in Max', 'Enterprise security', 'Storage & bandwidth boosts', 'Dedicated support', 'Custom integrations'],
        highlight: false,
        badge: 'Contact Sales',
      },
    ],
  },
  {
    id: 'mistral-lechat',
    name: 'Le Chat',
    provider: 'Mistral AI',
    providerId: 'mistralai',
    description: 'Mistral\'s AI assistant with frontier models, deep research, extended thinking, and No Telemetry Mode.',
    category: 'chat',
    url: 'https://chat.mistral.ai/pricing',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Mistral Medium & Small', '~25 messages/day', 'Code interpreter', 'Document uploads', 'AFP-verified news search'],
        highlight: false,
      },
      {
        name: 'Student',
        monthlyPrice: 7.04,
        annualMonthlyPrice: 7.04,
        perSeat: false,
        features: ['Full Pro access at 50%+ discount', 'All Mistral models', 'Verified student/educator pricing'],
        highlight: false,
        badge: 'Education',
      },
      {
        name: 'Pro',
        monthlyPrice: 14.99,
        annualMonthlyPrice: 6.99,
        perSeat: false,
        features: ['All models incl. Mistral Large', '~150 messages/day', '150 Flash Answers/day', '15 GB document storage', 'Deep research reports', 'Extended thinking', 'No Telemetry Mode'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Team',
        monthlyPrice: 24.99,
        annualMonthlyPrice: 19.99,
        perSeat: true,
        features: ['200 messages/seat', '30 GB storage', 'Google Drive & SharePoint connectors', 'RBAC & centralized billing', 'Admin controls & collaboration'],
        highlight: false,
      },
      {
        name: 'Enterprise',
        monthlyPrice: null,
        annualMonthlyPrice: null,
        perSeat: true,
        features: ['SAML SSO & audit logs', 'Self-hosted or private cloud', 'EU data residency', 'GDPR compliance', 'Dedicated support'],
        highlight: false,
        badge: 'Contact Sales',
      },
    ],
  },

  // ── Chinese AI Assistants ───────────────────────────────────────────────────
  {
    id: 'kimi',
    name: 'Kimi',
    provider: 'Moonshot AI',
    providerId: 'moonshotai',
    description: '月之暗面 (Moonshot AI) — long-context assistant with Deep Research and agentic tasks. Domestic pricing ~3–7× cheaper.',
    category: 'chat',
    url: 'https://kimi.ai/pricing',
    tiers: [
      {
        name: 'Adagio',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Unlimited basic chat', 'Kimi K2 model', 'Limited Deep Research', 'Limited agent tasks'],
        highlight: false,
      },
      {
        name: 'Andante',
        monthlyPrice: 19,
        annualMonthlyPrice: 16,
        cnMonthlyPrice: 49,
        cnAnnualMonthlyPrice: 42,
        perSeat: false,
        features: ['More Deep Research sessions', 'More agent task runs', 'API credit vouchers', 'Kimi K2 & advanced models'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Moderato',
        monthlyPrice: 39,
        annualMonthlyPrice: 33,
        cnMonthlyPrice: 99,
        cnAnnualMonthlyPrice: 88,
        perSeat: false,
        features: ['Concurrent Deep Research', '2,048 Kimi Code requests/wk', 'Top priority access', 'All models + early features'],
        highlight: false,
        badge: 'Power Users',
      },
      {
        name: 'Vivace',
        monthlyPrice: 199,
        annualMonthlyPrice: 199,
        perSeat: false,
        features: ['Priority access during peak hours', 'Maximum quota on all features', 'Dedicated compute allocation'],
        highlight: false,
        badge: 'Intl Only',
      },
    ],
  },
  {
    id: 'ernie-bot',
    name: 'ERNIE Bot',
    provider: 'Baidu',
    providerId: 'baidu',
    description: '文小言 (formerly 文心一言) — Baidu\'s AI assistant. Fully free since April 2025, including ERNIE 4.5 & X1 reasoning.',
    category: 'chat',
    url: 'https://yiyan.baidu.com/price',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['ERNIE 4.5 (unlimited)', 'ERNIE X1 reasoning model', 'Web search', 'Image generation', 'Document analysis', 'China-only access'],
        highlight: true,
        badge: 'Free Forever',
      },
    ],
  },
  {
    id: 'doubao',
    name: 'Doubao',
    provider: 'ByteDance',
    providerId: 'bytedance',
    description: '豆包 — ByteDance\'s AI assistant (Cici internationally) powered by Seed series models.',
    category: 'chat',
    url: 'https://www.doubao.com/price',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Doubao Pro (unlimited)', 'Seed Vision multimodal', 'Web search', 'File & image uploads', 'Voice conversations'],
        highlight: false,
      },
      {
        name: 'Pro',
        monthlyPrice: 9.99,
        annualMonthlyPrice: 8.33,
        cnMonthlyPrice: 40,
        perSeat: false,
        features: ['Higher usage limits', 'Priority access', 'Advanced model access', 'Coding-focused domestic plan (¥40/mo)', 'International via Google Play'],
        highlight: true,
        badge: 'Intl / Coding',
      },
    ],
  },

  {
    id: 'zhipu-ai',
    name: 'Z.ai (GLM)',
    provider: 'Zhipu AI',
    providerId: 'zhipuai',
    description: '智谱清言 — Zhipu AI\'s assistant powered by GLM-5. First major Chinese LLM to raise prices in 2026.',
    category: 'chat',
    url: 'https://chatglm.cn/membership',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['GLM-4.7 (open-source, self-hostable)', 'Basic chat', 'Limited usage'],
        highlight: false,
      },
      {
        name: 'Consumer',
        monthlyPrice: 4.41,
        annualMonthlyPrice: 3.59,
        cnMonthlyPrice: 32,
        cnAnnualMonthlyPrice: 26,
        perSeat: false,
        features: ['GLM-5 access', 'Higher usage limits', 'Priority compute', 'Prices raised ~30–60% Feb 2026 with GLM-5'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Coding Plan',
        monthlyPrice: 10,
        annualMonthlyPrice: 10,
        perSeat: false,
        features: ['GLM-5, GLM-5-Turbo, GLM-4.7', 'Works with Claude Code, Cline, Cursor', 'Developer-focused', 'API access included'],
        highlight: false,
        badge: 'Developers',
      },
    ],
  },

  // ── Search Assistants ────────────────────────────────────────────────────────

  // ── Coding Assistants ───────────────────────────────────────────────────────
  {
    id: 'cursor',
    name: 'Cursor',
    provider: 'Cursor',
    providerId: 'cursor',
    description: 'AI-first code editor with Tab completions, Agent mode, Cloud Agents, and Max Mode for frontier models.',
    category: 'coding',
    url: 'https://cursor.com/pricing',
    tiers: [
      {
        name: 'Hobby',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['50 premium requests + 500 free requests/mo', '7-day Pro trial', 'Tab completions (limited)', 'University students: 1-year free Pro'],
        highlight: false,
      },
      {
        name: 'Pro',
        monthlyPrice: 20,
        annualMonthlyPrice: 16,
        perSeat: false,
        features: ['Unlimited Tab completions', 'All frontier models (Claude, GPT-5, Gemini)', 'Cloud Agents (background tasks)', '$20 monthly credit pool', 'Unlimited Auto mode', 'Max context windows'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Pro+',
        monthlyPrice: 60,
        annualMonthlyPrice: 60,
        perSeat: false,
        features: ['All Pro features', '3× credit pool ($60 value)', 'Ideal for heavy usage'],
        highlight: false,
      },
      {
        name: 'Ultra',
        monthlyPrice: 200,
        annualMonthlyPrice: 200,
        perSeat: false,
        features: ['5,000 fast agent requests/mo', '20× Pro credit volume', 'Unlimited Max Mode compute', 'Priority access to experimental models', 'Dedicated onboarding support'],
        highlight: false,
        badge: 'Power Users',
      },
      {
        name: 'Teams',
        monthlyPrice: 40,
        annualMonthlyPrice: 32,
        perSeat: true,
        features: ['All Pro features per seat', 'SSO & RBAC', 'Admin dashboard', 'Shared chats', 'Centralized billing'],
        highlight: false,
      },
      {
        name: 'Enterprise',
        monthlyPrice: null,
        annualMonthlyPrice: null,
        perSeat: true,
        features: ['SCIM 2.0 provisioning', 'Audit logs', 'Pooled credits', 'AI code tracking API', 'Granular admin controls'],
        highlight: false,
        badge: 'Contact Sales',
      },
    ],
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    provider: 'Microsoft',
    providerId: 'microsoft',
    description: 'AI pair programmer in GitHub & VS Code with multi-model support, coding agent, and codebase indexing.',
    category: 'coding',
    url: 'https://github.com/features/copilot/plans',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['2,000 completions/mo', '50 premium requests/mo', 'Copilot Chat', 'Basic model selection'],
        highlight: false,
      },
      {
        name: 'Pro',
        monthlyPrice: 10,
        annualMonthlyPrice: 8.33,
        perSeat: false,
        features: ['Unlimited completions', '300 premium requests/mo', 'Copilot coding agent', 'Premium models in Chat', 'Students: free via GitHub Student Pack'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Pro+',
        monthlyPrice: 39,
        annualMonthlyPrice: 32.5,
        perSeat: false,
        features: ['1,500 premium requests/mo', 'Claude Opus 4 & OpenAI o3', 'All AI models', 'Copilot coding agent', 'Extra requests at $0.04 each'],
        highlight: false,
        badge: 'Power Users',
      },
      {
        name: 'Business',
        monthlyPrice: 19,
        annualMonthlyPrice: 19,
        perSeat: true,
        features: ['Unlimited completions', '300 premium requests/seat', 'Centralized management', 'IP indemnity & audit logs', 'Copilot policy controls'],
        highlight: false,
      },
      {
        name: 'Enterprise',
        monthlyPrice: 39,
        annualMonthlyPrice: 39,
        perSeat: true,
        features: ['All Business features', 'Codebase indexing', 'Knowledge bases', 'Fine-tuned custom models', '1,000 premium requests/seat'],
        highlight: false,
      },
    ],
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    provider: 'Windsurf',
    providerId: 'windsurf',
    description: 'Agentic AI code editor (by Cognition AI) with SWE-1 agent, Tab completions, and App Deploy.',
    category: 'coding',
    url: 'https://windsurf.com/pricing',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['25 prompt credits/mo', 'Unlimited Tab completions', 'SWE-1 Lite (no credits used)', '1 App Deploy/day', 'Unlimited Previews'],
        highlight: false,
      },
      {
        name: 'Pro',
        monthlyPrice: 15,
        annualMonthlyPrice: 15,
        perSeat: false,
        features: ['500 prompt credits/mo', 'All premium models incl. SWE-1', '5 App Deploys/day', 'Extra credits: $10/250'],
        highlight: true,
        badge: 'Best Value',
      },
      {
        name: 'Teams',
        monthlyPrice: 30,
        annualMonthlyPrice: 30,
        perSeat: true,
        features: ['500 credits/seat', 'Admin dashboard & analytics', 'Priority support', 'Optional SSO (+$10/seat)', 'Pooled credits: $40/1,000'],
        highlight: false,
      },
      {
        name: 'Enterprise',
        monthlyPrice: 60,
        annualMonthlyPrice: 60,
        perSeat: true,
        features: ['1,000 credits/seat', 'SSO & SCIM included', 'Longer context windows', 'Self-hosted / hybrid deployment', 'Zero Data Retention by default'],
        highlight: false,
      },
    ],
  },
  {
    id: 'claude-code',
    name: 'Claude Code',
    provider: 'Anthropic',
    providerId: 'anthropic',
    description: 'Agentic CLI coding tool for the terminal. Billed against your Anthropic API usage — no flat subscription.',
    category: 'coding',
    url: 'https://www.anthropic.com/claude-code',
    underlyingModels: ['anthropic/claude-sonnet-4-5'],
    tiers: [
      {
        name: 'API Usage',
        monthlyPrice: null,
        annualMonthlyPrice: null,
        perSeat: false,
        features: ['Pay per token at API rates', 'No subscription fee', 'Claude Sonnet default', 'Full autonomous coding', 'Included with Claude Max subscription'],
        highlight: true,
        badge: 'Usage-Based',
      },
    ],
  },
  // ── Media / Creative AI ──────────────────────────────────────────────────────
  {
    id: 'hailuo-ai',
    name: 'Hailuo AI',
    provider: 'MiniMax',
    providerId: 'minimax',
    description: 'MiniMax\'s Hailuo video & image generation platform. Hailuo 2.3 produces cinematic AI videos.',
    category: 'media',
    url: 'https://hailuo.ai/pricing',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['~500 one-time credits', 'Basic video generation', 'Watermarked output', '1 task at a time'],
        highlight: false,
      },
      {
        name: 'Standard',
        monthlyPrice: 9.99,
        annualMonthlyPrice: 9.99,
        perSeat: false,
        features: ['1,000 credits/mo', 'Fast-track generation', 'Watermark removal', '5 tasks in queue'],
        highlight: false,
      },
      {
        name: 'Pro',
        monthlyPrice: 34.99,
        annualMonthlyPrice: 34.99,
        perSeat: false,
        features: ['Priority queue', 'Hailuo 2.3 access', 'High-volume creation', 'No watermark'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Ultra',
        monthlyPrice: 124.99,
        annualMonthlyPrice: 124.99,
        perSeat: false,
        features: ['12,000+ credits/mo', 'Top queue priority', 'Hailuo 2.3 & 02 access', 'High-res export'],
        highlight: false,
      },
      {
        name: 'Max',
        monthlyPrice: 199.99,
        annualMonthlyPrice: 199.99,
        perSeat: false,
        features: ['12,000+ credits for newest models', 'Hailuo 2.3 & 02 full access', 'Maximum throughput', 'Commercial usage'],
        highlight: false,
        badge: 'Power Users',
      },
    ],
  },

  {
    id: 'microsoft-copilot',
    name: 'Microsoft Copilot',
    provider: 'Microsoft',
    providerId: 'microsoft',
    description: 'Microsoft\'s AI in Windows, Edge, Bing, and Microsoft 365 apps (Word, Excel, PowerPoint, Teams).',
    category: 'coding',
    url: 'https://www.microsoft.com/en-us/microsoft-365-copilot/pricing',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Copilot in Bing & Edge', '15 image boosts/day', 'Basic chat'],
        highlight: false,
      },
      {
        name: 'Copilot Pro',
        monthlyPrice: 20,
        annualMonthlyPrice: 20,
        perSeat: false,
        features: ['Priority access to latest models', '100 daily image boosts', 'Copilot in personal M365 apps', 'Researcher & Analyst (Excel)', 'Copilot Actions'],
        highlight: false,
      },
      {
        name: 'M365 Personal',
        monthlyPrice: 9.99,
        annualMonthlyPrice: 8.33,
        perSeat: false,
        features: ['Full Office apps (Word, Excel, PPT)', '1 TB OneDrive', 'Copilot in all apps', 'Microsoft Defender'],
        highlight: false,
      },
      {
        name: 'M365 Business',
        monthlyPrice: 21,
        annualMonthlyPrice: 18,
        perSeat: true,
        features: ['M365 Copilot in Teams, Word, Excel', 'Work IQ intelligence layer', 'Admin controls (up to 300 users)', 'Requires M365 Business Standard'],
        highlight: true,
        badge: 'Teams',
      },
    ],
  },
];
