import type { Subscription } from './types';

export const SUBSCRIPTIONS: Subscription[] = [
  // ── Chat AI Assistants ──────────────────────────────────────────────────────
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    provider: 'OpenAI',
    providerId: 'openai',
    description: 'The world\'s most popular AI assistant with GPT-5.6, image generation, and Codex agents.',
    category: 'chat',
    url: 'https://chatgpt.com/pricing',
    underlyingModels: ['openai/gpt-chat-latest', 'openai/gpt-5.6-sol', 'openai/gpt-5.6-sol-pro', 'openai/gpt-5.6-luna'],
    lastVerified: '2026-07-07',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Unlimited text chats with GPT-5.6 Luna', 'Limited messages with uploads', 'Limited and slower image generation', 'Limited deep research', 'Limited Codex access'],
        highlight: false,
      },
      {
        name: 'Go',
        monthlyPrice: 8,
        annualMonthlyPrice: 8,
        perSeat: false,
        features: ['Everything in Free, with more messages with tools', 'More uploads', 'More image creation', 'More voice chats', 'Longer memory', 'May include ads'],
        highlight: false,
      },
      {
        name: 'Plus',
        monthlyPrice: 20,
        annualMonthlyPrice: 20,
        perSeat: false,
        features: ['Advanced reasoning models with GPT-5.6', 'Expanded messages and uploads', 'Expanded deep research', 'Projects, scheduled tasks, and custom GPTs', 'Expanded Codex usage'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Pro 5×',
        monthlyPrice: 100,
        annualMonthlyPrice: 100,
        perSeat: false,
        features: ['5× Plus usage limits', 'Pro reasoning with GPT-5.6 Sol Pro', 'Maximum Codex tasks', 'Unlimited and faster image creation'],
        highlight: false,
      },
      {
        name: 'Pro 20×',
        monthlyPrice: 200,
        annualMonthlyPrice: 200,
        perSeat: false,
        features: ['20× Plus usage limits', 'Unlimited GPT-5.6 Sol Pro', 'Maximum deep research, memory and context', 'Research preview of new features'],
        highlight: false,
        badge: 'Max Power',
      },
      {
        name: 'Business',
        monthlyPrice: 25,
        annualMonthlyPrice: 20,
        perSeat: true,
        features: ['Everything in Plus', 'Minimum 2 seats', 'Shared workspace & Projects', 'Admin console', 'Data not used for training'],
        highlight: false,
      },
      {
        name: 'Enterprise',
        monthlyPrice: null,
        annualMonthlyPrice: null,
        perSeat: true,
        features: ['Unlimited GPT-5.6', 'SOC 2 & SSO', 'Analytics dashboards', 'Custom data retention', '24/7 priority support'],
        highlight: false,
        badge: 'Contact Sales',
      },
    ],
  },
  {
    id: 'claude-ai',
    name: 'Claude.ai',
    provider: 'Anthropic',
    providerId: 'anthropic',
    description: 'Anthropic\'s AI assistant with the Opus 5, Sonnet 5, and Fable 5 model lineup, Claude Code, and Cowork agent delegation.',
    category: 'chat',
    url: 'https://claude.com/pricing',
    lastVerified: '2026-08-17',
    underlyingModels: ['anthropic/claude-opus-5', 'anthropic/claude-sonnet-5', 'anthropic/claude-fable-5'],
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Claude Sonnet (limited)', 'Web search & file analysis', 'Basic Projects'],
        highlight: false,
      },
      {
        name: 'Pro',
        monthlyPrice: 20,
        annualMonthlyPrice: 17,
        perSeat: false,
        features: ['~45 prompts / 5-hr window', 'All models incl. Opus 5 & Sonnet 5', 'Fable 5 via usage credits', 'Claude Code included', 'Cowork, Design & Science tools', 'Unlimited Projects'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Max 5×',
        monthlyPrice: 100,
        annualMonthlyPrice: 100,
        perSeat: false,
        features: ['5× Pro usage limits', 'Higher output limits', 'Priority routing at peak', 'Early access to new features'],
        highlight: false,
      },
      {
        name: 'Max 20×',
        monthlyPrice: 200,
        annualMonthlyPrice: 200,
        perSeat: false,
        features: ['20× Pro usage limits', 'Effectively no daily limits', 'Maximum priority routing', 'All Max 5× features'],
        highlight: false,
        badge: 'Power Users',
      },
      {
        name: 'Team Standard',
        monthlyPrice: 25,
        annualMonthlyPrice: 20,
        perSeat: true,
        features: ['Pro-level usage per seat', 'Enterprise search', 'SSO & central admin', 'Shared projects', 'No training on team data'],
        highlight: false,
      },
      {
        name: 'Team Premium',
        monthlyPrice: 125,
        annualMonthlyPrice: 100,
        perSeat: true,
        features: ['5× more usage than Standard seats', 'Fable 5 via usage credits', 'Priority support', 'All Standard features'],
        highlight: false,
        badge: 'Power Teams',
      },
      {
        name: 'Enterprise',
        monthlyPrice: null,
        annualMonthlyPrice: null,
        perSeat: true,
        features: ['SCIM provisioning & audit logs', 'HIPAA-ready & compliance API', 'Custom data retention', 'Role-based access', 'Dedicated support'],
        highlight: false,
        badge: 'Contact Sales',
      },
    ],
  },
  {
    id: 'gemini',
    name: 'Google AI',
    provider: 'Google',
    providerId: 'google',
    description: 'Google\'s AI suite — Gemini 3.1 Pro & 3.6 Flash, Gemini Omni video, Deep Research, NotebookLM, and Flow credits.',
    category: 'chat',
    url: 'https://gemini.google/subscriptions/',
    lastVerified: '2026-08-17',
    underlyingModels: ['google/gemini-3.1-pro-preview', 'google/gemini-3.6-flash'],
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Gemini 3.6 Flash + varying 3.1 Pro access', 'Basic Deep Research', 'Google integrations', 'Limited Audio Overviews'],
        highlight: false,
      },
      {
        name: 'AI Plus',
        monthlyPrice: 4.99,
        annualMonthlyPrice: 4.99,
        perSeat: false,
        features: ['Cut from $7.99 in June 2026', '2× Free usage limits', 'Google Flow video (Gemini Omni)', 'Daily Brief + 200 Flow credits', '400 GB storage', 'Family sharing (up to 5)'],
        highlight: false,
      },
      {
        name: 'AI Pro',
        monthlyPrice: 19.99,
        annualMonthlyPrice: 19.99,
        perSeat: false,
        features: ['Gemini 3.1 Pro + 1M context', '4× Free limits, full Deep Research', 'NotebookLM in Pro', 'Jules & Antigravity coding agents', '1,000 Flow credits', '5 TB storage', 'YouTube Premium Lite'],
        highlight: true,
        badge: 'Best Value',
      },
      {
        name: 'AI Ultra (5×)',
        monthlyPrice: 99.99,
        annualMonthlyPrice: 99.99,
        perSeat: false,
        features: ['5× Pro usage limits', 'Deep Think reasoning', '10,000 Flow credits', '20 TB storage', 'Gemini Spark (US) & YouTube Premium'],
        highlight: false,
      },
      {
        name: 'AI Ultra (20×)',
        monthlyPrice: 199.99,
        annualMonthlyPrice: 199.99,
        perSeat: false,
        features: ['20× Pro usage limits', 'Project Genie (20× exclusive)', '25,000 Flow credits', 'YouTube Premium included', 'Google Home Premium Advanced', 'Cut from $249.99 at I/O 2026'],
        highlight: false,
        badge: 'Max Power',
      },
    ],
  },
  {
    id: 'grok',
    name: 'Grok',
    provider: 'xAI',
    providerId: 'x-ai',
    description: 'xAI\'s AI with real-time X data and Search, Grok 4.6, and agentic Imagine tools.',
    category: 'chat',
    url: 'https://x.ai/pricing',
    lastVerified: '2026-08-17',
    underlyingModels: ['x-ai/grok-4.6', 'x-ai/grok-4.5'],
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Real-time web and X search', 'Voice mode', 'Connectors', 'SOC 2 compliance (Type I & II)'],
        highlight: false,
      },
      {
        name: 'X Premium',
        monthlyPrice: 8,
        annualMonthlyPrice: 8,
        perSeat: false,
        features: ['Basic Grok access within X', 'Blue checkmark', 'Ad revenue sharing'],
        highlight: false,
      },
      {
        name: 'X Premium+',
        monthlyPrice: 40,
        annualMonthlyPrice: 40,
        perSeat: false,
        features: ['Priority Grok access within X', 'Grok 4.3 access', 'Ad-free X browsing', 'Full X social features'],
        highlight: false,
      },
      {
        name: 'SuperGrok Lite',
        monthlyPrice: 10,
        annualMonthlyPrice: 10,
        perSeat: false,
        features: ['Entry standalone tier (Mar 2026)', 'Grok Imagine', '1 AI agent', 'grok.com + mobile apps'],
        highlight: false,
      },
      {
        name: 'SuperGrok',
        monthlyPrice: 30,
        annualMonthlyPrice: 25,
        perSeat: false,
        features: ['Grok 4.6 model access', 'Search & Multi-agent mode', 'Higher rate limits across all features', 'Image and video generation', 'Connectors'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'SuperGrok Plus',
        monthlyPrice: 100,
        annualMonthlyPrice: 100,
        perSeat: false,
        features: ['Everything in SuperGrok', 'Create 1080p videos', 'Significantly higher usage across Chat, Imagine, Voice & Build', 'Priority access at peak times', 'Early access to new features'],
        highlight: false,
      },
      {
        name: 'SuperGrok Heavy',
        monthlyPrice: 300,
        annualMonthlyPrice: 300,
        perSeat: false,
        features: ['Grok 4.6 full access', 'Grok 4 Heavy multi-agent compute', 'Maximum rate limits', 'Early access to all new features', 'Priority voice'],
        highlight: false,
        badge: 'Max Power',
      },
    ],
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    provider: 'Perplexity',
    providerId: 'perplexityai',
    description: 'AI-powered answer engine with real-time web search, citations, and Create (files & apps) tools.',
    category: 'search',
    url: 'https://perplexity.ai/pro',
    lastVerified: '2026-08-17',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['5 Pro searches/day', 'Unlimited standard searches', 'Web citations', 'Basic file uploads'],
        highlight: false,
      },
      {
        name: 'Pro',
        monthlyPrice: 20,
        annualMonthlyPrice: 17,
        perSeat: false,
        features: ['300+ Pro searches/day', 'Frontier models (Sonar 2, GPT-5.6 Terra, Claude Sonnet 5, Gemini 3.7 Flash)', 'Unlimited file uploads', 'Image generation', '$5/mo API credits', 'Standard Create access'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Max',
        monthlyPrice: 200,
        annualMonthlyPrice: 167,
        perSeat: false,
        features: ['Unlimited Create (dashboards, apps, spreadsheets)', 'Model Council (3 frontier models in parallel)', 'Computer (background & scheduled tasks)', '10,000 Computer credits/mo', 'Veo 3.1 video generation', 'Priority support'],
        highlight: false,
        badge: 'Power Users',
      },
      {
        name: 'Enterprise Pro',
        monthlyPrice: 40,
        annualMonthlyPrice: 40,
        perSeat: true,
        features: ['Everything in Pro', 'Team dashboard', 'Centralized billing', 'SOC 2 compliance', 'Data never used for training'],
        highlight: false,
      },
      {
        name: 'Enterprise Max',
        monthlyPrice: 325,
        annualMonthlyPrice: 270.83,
        perSeat: true,
        features: ['Everything in Max', 'Enterprise security', 'Storage & bandwidth boosts', 'Dedicated support', 'Custom integrations'],
        highlight: false,
        badge: 'Contact Sales',
      },
    ],
  },
  {
    id: 'mistral-lechat',
    name: 'Le Chat (Vibe)',
    provider: 'Mistral AI',
    providerId: 'mistralai',
    description: 'Mistral\'s AI assistant — rebranded "Vibe" in 2026 — with frontier models, deep research, extended thinking, and No Telemetry Mode.',
    category: 'chat',
    url: 'https://mistral.ai/pricing',
    lastVerified: '2026-08-17',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Mistral Medium & Small', '~25 messages/day', 'Code interpreter', 'Document uploads', 'AFP-verified news search'],
        highlight: false,
      },
      {
        name: 'Student',
        monthlyPrice: 5.99,
        annualMonthlyPrice: 5.99,
        perSeat: false,
        features: ['Full Pro access at a discount', 'All Mistral models', 'Verified student/educator pricing'],
        highlight: false,
        badge: 'Education',
      },
      {
        name: 'Pro',
        monthlyPrice: 14.99,
        annualMonthlyPrice: 11.99,
        perSeat: false,
        features: ['All models incl. Mistral Large', '~150 messages/day', '150 Flash Answers/day', '15 GB document storage', 'Deep research reports', 'Extended thinking', 'No Telemetry Mode'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Team',
        monthlyPrice: 24.99,
        annualMonthlyPrice: 19.99,
        perSeat: true,
        features: ['200 messages/seat', '30 GB storage', 'Google Drive & SharePoint connectors', 'RBAC & centralized billing', 'Admin controls & collaboration'],
        highlight: false,
      },
      {
        name: 'Enterprise',
        monthlyPrice: null,
        annualMonthlyPrice: null,
        perSeat: true,
        features: ['SAML SSO & audit logs', 'Self-hosted or private cloud', 'EU data residency', 'GDPR compliance', 'Dedicated support'],
        highlight: false,
        badge: 'Contact Sales',
      },
    ],
  },

  // ── Chinese AI Assistants ───────────────────────────────────────────────────
  {
    id: 'kimi',
    name: 'Kimi',
    provider: 'Moonshot AI',
    providerId: 'moonshotai',
    description: '月之暗面 (Moonshot AI) — long-context assistant powered by Kimi K3, with Deep Research and agentic tasks. Tiers shown are international (USD); domestic China is a separate, cheaper ¥ ladder (Andante ¥49 to Allegro ¥699/mo).',
    category: 'chat',
    url: 'https://www.kimi.com/pricing',
    lastVerified: '2026-07-07',
    tiers: [
      {
        name: 'Adagio',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Unlimited basic chat', 'Kimi K2.6 model', 'Limited Deep Research', 'Limited agent tasks'],
        highlight: false,
      },
      {
        name: 'Moderato',
        monthlyPrice: 19,
        annualMonthlyPrice: 15,
        perSeat: false,
        features: ['Entry paid tier (was $39)', 'More Deep Research & agent runs', 'Kimi K2.6 & advanced models', 'API credit vouchers'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Allegretto',
        monthlyPrice: 39,
        annualMonthlyPrice: 31,
        perSeat: false,
        features: ['Concurrent Deep Research', 'Higher weekly Kimi Code quota', 'Priority access', 'All models + early features'],
        highlight: false,
      },
      {
        name: 'Allegro',
        monthlyPrice: 99,
        annualMonthlyPrice: 79,
        perSeat: false,
        features: ['Maximum quotas on all features', 'Top priority during peak hours', 'Highest Kimi Code limits'],
        highlight: false,
      },
      {
        name: 'Vivace',
        monthlyPrice: 199,
        annualMonthlyPrice: 159,
        perSeat: false,
        features: ['Dedicated compute allocation', 'Absolute maximum quota', 'International-only top tier'],
        highlight: false,
        badge: 'Max Power',
      },
    ],
  },
  {
    id: 'ernie-bot',
    name: 'ERNIE Bot',
    provider: 'Baidu',
    providerId: 'baidu',
    description: '文心 (formerly 文小言 / 文心一言) — Baidu\'s AI assistant. Fully free since April 2025, now powered by ERNIE 5.1.',
    category: 'chat',
    url: 'https://yiyan.baidu.com/',
    lastVerified: '2026-07-07',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['ERNIE 5.1 (unlimited)', 'ERNIE 5.0 multimodal reasoning', 'Web search', 'Image & video generation', 'Document analysis', 'China-only access'],
        highlight: true,
        badge: 'Free Forever',
      },
    ],
  },
  {
    id: 'doubao',
    name: 'Doubao',
    provider: 'ByteDance',
    providerId: 'bytedance',
    description: '豆包 — ByteDance\'s AI assistant (Dola internationally, formerly Cici), powered by Doubao Seed 2.1. Ended its free-only era in June 2026; paid tiers are China-domestic (¥) — international Dola pricing is not publicly confirmed.',
    category: 'chat',
    url: 'https://www.doubao.com/',
    lastVerified: '2026-07-07',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Doubao 2.1 Turbo (quota-limited)', 'Seed Vision multimodal', 'Web search', 'File & image uploads', 'Voice conversations'],
        highlight: false,
      },
      {
        name: 'Standard',
        monthlyPrice: null,
        annualMonthlyPrice: null,
        cnMonthlyPrice: 68,
        perSeat: false,
        features: ['5× the free-tier quota', 'Doubao Seed 2.1 Pro', 'AI PPT & spreadsheets', 'Deep research & expert mode', 'Student plan ¥38/mo'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Enhanced',
        monthlyPrice: null,
        annualMonthlyPrice: null,
        cnMonthlyPrice: 200,
        perSeat: false,
        features: ['4× the Standard quota', 'Higher limits for heavy use', 'Priority access', 'Full Seed 2.1 Pro features'],
        highlight: false,
      },
      {
        name: 'Premium',
        monthlyPrice: null,
        annualMonthlyPrice: null,
        cnMonthlyPrice: 500,
        perSeat: false,
        features: ['10× the Standard quota', 'Maximum quotas on all features', 'Top-priority compute', 'For the heaviest users'],
        highlight: false,
        badge: 'Power Users',
      },
    ],
  },

  {
    id: 'zhipu-ai',
    name: 'Z.ai (GLM)',
    provider: 'Zhipu AI',
    providerId: 'zhipuai',
    description: '智谱清言 — Zhipu AI\'s assistant powered by GLM-5.3. Consumer chat is free on open-source GLM-4.7; the paid GLM Coding Plan is the flagship offering. List prices shown — a standing promo runs ~30% lower.',
    category: 'chat',
    url: 'https://z.ai/subscribe',
    lastVerified: '2026-08-17',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['GLM-4.7 (open-source, self-hostable)', 'Basic chat', 'Limited usage'],
        highlight: false,
      },
      {
        name: 'Coding Lite',
        monthlyPrice: 18,
        annualMonthlyPrice: 18,
        cnMonthlyPrice: 49,
        perSeat: false,
        features: ['GLM-5.3, GLM-5.2, GLM-5-Turbo', 'Works with Claude Code, Cline, Cursor', '~80 prompts / 5 hrs', '100 MCP calls/mo', 'API access included'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Coding Pro',
        monthlyPrice: 80,
        annualMonthlyPrice: 80,
        cnMonthlyPrice: 149,
        perSeat: false,
        features: ['~400 prompts / 5 hrs', '1,000 MCP calls/mo', 'All GLM coding models', 'Priority access'],
        highlight: false,
        badge: 'Developers',
      },
      {
        name: 'Coding Max',
        monthlyPrice: 168,
        annualMonthlyPrice: 168,
        cnMonthlyPrice: 469,
        perSeat: false,
        features: ['~1,600 prompts / 5 hrs', '4,000 MCP calls/mo', 'Maximum quotas', 'For heavy agentic coding'],
        highlight: false,
        badge: 'Power Users',
      },
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    provider: 'DeepSeek',
    providerId: 'deepseek',
    description: '深度求索 — free frontier assistant powered by DeepSeek-V4. No consumer paywall; monetizes via its ultra-cheap API.',
    category: 'chat',
    url: 'https://chat.deepseek.com',
    lastVerified: '2026-07-11',
    underlyingModels: ['deepseek/deepseek-v4-pro', 'deepseek/deepseek-v4-flash'],
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['DeepSeek-V4 chat (unlimited)', 'Thinking mode (DeepThink)', 'Web search', 'File upload & analysis', 'No message caps or feature gates'],
        highlight: true,
        badge: 'Free Forever',
      },
    ],
  },
  {
    id: 'qwen-chat',
    name: 'Qwen Studio',
    provider: 'Alibaba',
    providerId: 'qwen',
    description: 'Qwen Studio (formerly 通义千问 / Qwen Chat) — Alibaba\'s assistant powered by Qwen3.7. Free consumer app; monetizes via Alibaba Cloud API.',
    category: 'chat',
    url: 'https://chat.qwen.ai',
    lastVerified: '2026-07-11',
    underlyingModels: ['qwen/qwen3.7-max', 'qwen/qwen3.7-plus'],
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Qwen3.7 models (unlimited)', 'Thinking & web search modes', 'Image, video & audio understanding', 'Artifacts & code preview'],
        highlight: true,
        badge: 'Free Forever',
      },
    ],
  },

  {
    id: 'meta-ai',
    name: 'Meta AI',
    provider: 'Meta',
    providerId: 'meta-llama',
    description: 'Meta\'s free assistant across Facebook, Instagram, WhatsApp, Messenger, and meta.ai — powered by Muse Spark 1.1 from Meta Superintelligence Labs. Paid Meta One Plus/Premium tiers are in limited testing with no published pricing.',
    category: 'chat',
    url: 'https://www.meta.ai/',
    lastVerified: '2026-07-11',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Muse Spark 1.1 (1M-token context)', 'In FB, IG, WhatsApp & Messenger', 'Thinking mode (app & meta.ai only)', 'Image & video generation (base)'],
        highlight: true,
        badge: 'Free',
      },
    ],
  },
  {
    id: 'manus',
    name: 'Manus',
    provider: 'Manus',
    providerId: 'manus',
    description: 'General AI agent (research, coding, websites, slides, browser automation) on Manus 1.6 — announced Aug 2026 that it will resume operating as an independent company. Credit-based ladder; the $40 tier scales up to 20,000 credits.',
    category: 'chat',
    url: 'https://manus.im/pricing',
    lastVerified: '2026-08-17',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Limited monthly credits', 'Core agent capabilities'],
        highlight: false,
      },
      {
        name: 'Pro 4K',
        monthlyPrice: 20,
        annualMonthlyPrice: 17,
        perSeat: false,
        features: ['4,000 credits/mo', '300 daily refresh credits', 'Wide Research', '20 concurrent + 20 scheduled tasks'],
        highlight: true,
      },
      {
        name: 'Pro 8–20K',
        monthlyPrice: 40,
        annualMonthlyPrice: 34,
        perSeat: false,
        features: ['8,000 credits/mo at $40', 'Scales to 20,000 credits (~$5 per extra 1K)', 'All Pro features'],
        highlight: false,
      },
      {
        name: 'Pro 40K',
        monthlyPrice: 200,
        annualMonthlyPrice: 167,
        perSeat: false,
        features: ['40,000 credits/mo', 'Free Cloud Computer', 'Early access to betas'],
        highlight: false,
        badge: 'Power Users',
      },
      {
        name: 'Team',
        monthlyPrice: 20,
        annualMonthlyPrice: 16.67,
        perSeat: true,
        features: ['4,000 credits/seat pooled', 'Admin dashboard & SSO', 'Shared projects & skills', 'SOC 2 + ISO 27001'],
        highlight: false,
      },
    ],
  },

  // ── Search Assistants ────────────────────────────────────────────────────────

  // ── Coding Assistants ───────────────────────────────────────────────────────
  {
    id: 'cursor',
    name: 'Cursor',
    provider: 'Cursor',
    providerId: 'cursor',
    description: 'AI-first code editor with Tab completions, Agent mode, Cloud Agents, MCPs & hooks, and Bugbot code review on frontier models.',
    category: 'coding',
    url: 'https://cursor.com/pricing',
    lastVerified: '2026-08-17',
    tiers: [
      {
        name: 'Hobby',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['No credit card required', 'Limited Agent requests', 'Limited Tab completions'],
        highlight: false,
      },
      {
        name: 'Pro',
        monthlyPrice: 20,
        annualMonthlyPrice: 16,
        perSeat: false,
        features: ['Extended limits on Agent', 'Generous limits for Grok & Composer', 'Access to frontier models', 'MCPs, skills, and hooks', 'Cloud agents', 'Bugbot on usage-based billing'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Pro+',
        monthlyPrice: 60,
        annualMonthlyPrice: 48,
        perSeat: false,
        features: ['All Pro features', '3× Pro limits on Agent', 'Ideal for heavy usage'],
        highlight: false,
      },
      {
        name: 'Ultra',
        monthlyPrice: 200,
        annualMonthlyPrice: 160,
        perSeat: false,
        features: ['20× Pro limits on Agent', 'Access to frontier models', 'MCPs, skills, and hooks', 'Cloud agents', 'Priority access to new features'],
        highlight: false,
        badge: 'Power Users',
      },
      {
        name: 'Teams Standard',
        monthlyPrice: 40,
        annualMonthlyPrice: 32,
        perSeat: true,
        features: ['All Pro features per seat', 'SSO & RBAC', 'Admin dashboard', 'Shared chats', 'Centralized billing'],
        highlight: false,
      },
      {
        name: 'Teams Premium',
        monthlyPrice: 120,
        annualMonthlyPrice: 96,
        perSeat: true,
        features: ['All Teams Standard features', '5× Standard limits on Agent', 'Team marketplace for rules, skills & plugins', 'Agentic code reviews with Bugbot', 'Team-wide privacy mode'],
        highlight: false,
      },
      {
        name: 'Enterprise',
        monthlyPrice: null,
        annualMonthlyPrice: null,
        perSeat: true,
        features: ['SCIM 2.0 provisioning', 'Audit logs', 'Pooled credits', 'AI code tracking API', 'Granular admin controls'],
        highlight: false,
        badge: 'Contact Sales',
      },
    ],
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    provider: 'Microsoft',
    providerId: 'microsoft',
    description: 'AI pair programmer in GitHub & VS Code with multi-model support, Copilot cloud agent, and repository indexing.',
    category: 'coding',
    url: 'https://github.com/features/copilot/plans',
    lastVerified: '2026-08-17',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['2,000 completions/mo', 'Haiku 4.5 & GPT-5 mini (auto model selection)', 'Copilot CLI', 'Community support'],
        highlight: false,
      },
      {
        name: 'Pro',
        monthlyPrice: 10,
        annualMonthlyPrice: 8.33,
        perSeat: false,
        features: ['Unlimited completions', '$15/mo in GitHub AI Credits', 'Copilot cloud agent & code review', '3rd-party agents (Claude Code, Codex)', 'Free for verified students'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Pro+',
        monthlyPrice: 39,
        annualMonthlyPrice: 32.5,
        perSeat: false,
        features: ['$70/mo in GitHub AI Credits', 'Claude Opus 4.7/4.8 & Fable 5', 'Broad premium model catalog', 'Copilot cloud agent & code review', 'Overage billed as AI Credits'],
        highlight: false,
        badge: 'Power Users',
      },
      {
        name: 'Max',
        monthlyPrice: 100,
        annualMonthlyPrice: 100,
        perSeat: false,
        features: ['$100/mo in GitHub AI Credits', 'Built for sustained agent-driven workflows', 'Everything in Pro+', 'Highest individual usage ceiling'],
        highlight: false,
      },
      {
        name: 'Business',
        monthlyPrice: 19,
        annualMonthlyPrice: 19,
        perSeat: true,
        features: ['Unlimited completions', 'Seat-pooled GitHub AI Credits', 'Centralized management', 'IP indemnity & audit logs', 'Copilot policy controls'],
        highlight: false,
      },
      {
        name: 'Enterprise',
        monthlyPrice: 39,
        annualMonthlyPrice: 39,
        perSeat: true,
        features: ['All Business features', 'Repository indexing (semantic code search)', 'Copilot Spaces (replaced Knowledge bases)', 'Larger monthly AI Credits pool'],
        highlight: false,
      },
    ],
  },
  {
    id: 'windsurf',
    name: 'Devin (Windsurf)',
    provider: 'Cognition',
    providerId: 'windsurf',
    description: 'Cognition\'s AI software engineer. The Windsurf editor is now Devin Desktop — one plan covers the IDE, cloud agents, and Devin sessions.',
    category: 'coding',
    url: 'https://devin.ai/pricing',
    lastVerified: '2026-08-17',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Light agent quota', 'Unlimited Tab & inline edits', 'Devin Desktop (ex-Windsurf) included', 'Limited model availability'],
        highlight: false,
      },
      {
        name: 'Pro',
        monthlyPrice: 20,
        annualMonthlyPrice: 20,
        perSeat: false,
        features: ['Higher agent quotas', 'OpenAI, Claude & Gemini models', 'SWE-1.7 & open-source models free', 'Cloud agents'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Max',
        monthlyPrice: 200,
        annualMonthlyPrice: 200,
        perSeat: false,
        features: ['Everything in Pro', 'Significantly higher usage quotas', 'For heavy agent users'],
        highlight: false,
        badge: 'Power Users',
      },
      {
        name: 'Teams',
        monthlyPrice: 40,
        annualMonthlyPrice: 40,
        perSeat: true,
        features: ['+$80/mo team base fee', 'Unlimited team members', 'Admin dashboard & analytics', 'Centralized billing', 'Priority support'],
        highlight: false,
      },
      {
        name: 'Enterprise',
        monthlyPrice: null,
        annualMonthlyPrice: null,
        perSeat: true,
        features: ['SAML/OIDC SSO', 'Dedicated deployment option', 'Centralized enterprise controls', 'Dedicated account management'],
        highlight: false,
        badge: 'Contact Sales',
      },
    ],
  },
  {
    id: 'claude-code',
    name: 'Claude Code',
    provider: 'Anthropic',
    providerId: 'anthropic',
    description: 'Agentic coding tool for terminal, IDE, web, and desktop. Included with Claude Pro/Max/Team plans — or pay-as-you-go via API.',
    category: 'coding',
    url: 'https://www.anthropic.com/claude-code',
    lastVerified: '2026-08-17',
    underlyingModels: ['anthropic/claude-opus-5', 'anthropic/claude-sonnet-5', 'anthropic/claude-fable-5'],
    tiers: [
      {
        name: 'Included w/ Plans',
        monthlyPrice: null,
        annualMonthlyPrice: null,
        perSeat: false,
        features: ['Included with Pro ($20) & Max plans', 'Or pay per token at API rates', 'Opus 5, Sonnet 5 & Fable 5', 'Terminal, IDE, web & desktop apps', 'Usage draws from your plan limits'],
        highlight: true,
        badge: 'Bundled',
      },
    ],
  },
  {
    id: 'replit',
    name: 'Replit',
    provider: 'Replit',
    providerId: 'replit',
    description: 'Cloud IDE where Replit Agent 4 builds and ships full-stack apps from prompts. The per-seat Teams plan was sunset in March 2026 — flat-rate Pro is the team option now.',
    category: 'coding',
    url: 'https://replit.com/pricing',
    lastVerified: '2026-08-17',
    tiers: [
      {
        name: 'Starter',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Limited Agent credits to try', 'Publish 1 app', 'Built-in database & design tools', 'Private deployments'],
        highlight: false,
      },
      {
        name: 'Core',
        monthlyPrice: 25,
        annualMonthlyPrice: 20,
        perSeat: false,
        features: ['$25/mo of Agent credits', 'Replit Agent 4', 'Up to 5 collaborators, 2 parallel agents', 'Unlimited workspaces', 'Remove "Made with Replit" badge'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Pro',
        monthlyPrice: 100,
        annualMonthlyPrice: 95,
        perSeat: false,
        features: ['$100/mo pooled credits (flat rate, not per-seat)', 'Up to 15 builders + 50 viewers', '10 parallel agents', 'Most powerful models', '28-day database rollback'],
        highlight: false,
        badge: 'Teams',
      },
      {
        name: 'Enterprise',
        monthlyPrice: null,
        annualMonthlyPrice: null,
        perSeat: true,
        features: ['SSO/SAML', 'Custom seat limits', 'VPC peering & static IPs', 'Single-tenant option', 'Dedicated support'],
        highlight: false,
        badge: 'Contact Sales',
      },
    ],
  },
  {
    id: 'lovable',
    name: 'Lovable',
    provider: 'Lovable',
    providerId: 'lovable',
    description: 'AI app builder turning prompts into live full-stack web apps via agentic multi-model orchestration on Claude models. Credit-priced plans — unlimited workspace members on every tier.',
    category: 'coding',
    url: 'https://lovable.dev/pricing',
    lastVerified: '2026-08-17',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['5 daily build credits (up to 30/mo)', 'Unlimited collaborators', '5 lovable.app domains', 'Cloud & community support'],
        highlight: false,
      },
      {
        name: 'Pro',
        monthlyPrice: 25,
        annualMonthlyPrice: 21,
        perSeat: false,
        features: ['100 monthly credits + rollovers', 'Custom domains', 'Per-member credit limits', 'Remove Lovable badge', 'Students: 50% off'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Business',
        monthlyPrice: 50,
        annualMonthlyPrice: 42,
        perSeat: false,
        features: ['All Pro features (same 100 credits)', 'Team workspace & role-based access', 'SSO & security center', 'Internal publish', 'Priority support'],
        highlight: false,
      },
      {
        name: 'Enterprise',
        monthlyPrice: null,
        annualMonthlyPrice: null,
        perSeat: false,
        features: ['Platform fee + volume-based pricing', 'SCIM & audit logs', 'Custom connectors', 'Dedicated support & onboarding'],
        highlight: false,
        badge: 'Contact Sales',
      },
    ],
  },
  {
    id: 'v0',
    name: 'v0 by Vercel',
    provider: 'Vercel',
    providerId: 'vercel',
    description: 'Vercel\'s AI app builder — prompts to deployed full-stack apps, metered through its own v0 Mini/Pro/Max model tiers. No annual billing; credits expire after 65 days.',
    category: 'coding',
    url: 'https://v0.app/pricing',
    lastVerified: '2026-08-17',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['$5 monthly credits', '7 messages/day cap', 'Deploy to Vercel', 'Design Mode & GitHub sync'],
        highlight: false,
      },
      {
        name: 'Plus',
        monthlyPrice: 30,
        annualMonthlyPrice: 30,
        perSeat: true,
        features: ['$30 credits/user + $2/day login bonus', 'v0 Mini, Pro & Max models', 'Add-on credit purchases', 'Shared chats & centralized billing'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Business',
        monthlyPrice: 100,
        annualMonthlyPrice: 100,
        perSeat: true,
        features: ['Same credits as Team', 'Training opt-out by default', 'Centralized billing'],
        highlight: false,
      },
      {
        name: 'Enterprise',
        monthlyPrice: null,
        annualMonthlyPrice: null,
        perSeat: true,
        features: ['No training on data', 'SAML SSO & RBAC', 'Priority performance', 'Support SLAs'],
        highlight: false,
        badge: 'Contact Sales',
      },
    ],
  },
  // ── Media / Creative AI ──────────────────────────────────────────────────────
  {
    id: 'midjourney',
    name: 'Midjourney',
    provider: 'Midjourney',
    providerId: 'midjourney',
    description: 'The reference AI image & video generator, currently on V8.1. Subscription-only — no free tier; annual billing is 20% off.',
    category: 'media',
    url: 'https://docs.midjourney.com/hc/en-us/articles/27870484040333-Comparing-Midjourney-Plans',
    lastVerified: '2026-08-17',
    tiers: [
      {
        name: 'Basic',
        monthlyPrice: 10,
        annualMonthlyPrice: 8,
        perSeat: false,
        features: ['3.3 fast GPU hrs/mo (~200 images)', 'SD video generation (1 fast job)', 'No relax mode', 'General commercial terms'],
        highlight: false,
      },
      {
        name: 'Standard',
        monthlyPrice: 30,
        annualMonthlyPrice: 24,
        perSeat: false,
        features: ['15 fast GPU hrs/mo', 'Unlimited relax image generations', 'HD video generation', 'General commercial terms'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Pro',
        monthlyPrice: 60,
        annualMonthlyPrice: 48,
        perSeat: false,
        features: ['30 fast GPU hrs/mo', 'Stealth mode (private creations)', 'Unlimited relax generations', 'Required for companies >$1M revenue'],
        highlight: false,
      },
      {
        name: 'Mega',
        monthlyPrice: 120,
        annualMonthlyPrice: 96,
        perSeat: false,
        features: ['60 fast GPU hrs/mo', 'Stealth mode', 'Unlimited relax generations', 'Maximum throughput'],
        highlight: false,
        badge: 'Power Users',
      },
    ],
  },
  {
    id: 'hailuo-ai',
    name: 'Hailuo AI',
    provider: 'MiniMax',
    providerId: 'minimax',
    description: 'MiniMax\'s Hailuo video & image generator — a multi-model hub led by MiniMax H3, with Veo 3.1, Sora 2 & Seedance 2.0. Annual billing runs ~47% cheaper than monthly.',
    category: 'media',
    url: 'https://hailuoai.video/subscribe',
    lastVerified: '2026-07-11',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['One-time free trial credits (0 monthly)', 'Hailuo models only', 'Watermarked output', '1 task at a time'],
        highlight: false,
      },
      {
        name: 'Standard',
        monthlyPrice: 14.99,
        annualMonthlyPrice: 7.99,
        perSeat: false,
        features: ['1,000 credits/mo (~83 videos)', 'Watermark removal', 'Access to Veo 3.1 & Sora 2', 'Seedance 2.0 at −50% credits'],
        highlight: false,
      },
      {
        name: 'Pro',
        monthlyPrice: 54.99,
        annualMonthlyPrice: 27.99,
        perSeat: false,
        features: ['4,500 credits/mo (~375 videos)', 'Nano Banana Pro & Seedream unlimited (1–2K)', 'GPT Image 1.5 & Light Studio unlimited', '8-task queue'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Master',
        monthlyPrice: 119.99,
        annualMonthlyPrice: 63.99,
        perSeat: false,
        features: ['10,500 credits/mo (~875 videos)', '2 parallel tasks', 'Nano Banana Pro/2 at 2K unlimited', 'Access to Veo 3.1 & Sora 2'],
        highlight: false,
      },
      {
        name: 'Max',
        monthlyPrice: 199.99,
        annualMonthlyPrice: 199.99,
        perSeat: false,
        features: ['20,000 credits/mo (~1,666 videos)', 'Hailuo 2.3/2.0/1.0 unlimited', 'Midjourney V7 & Niji7 image gen', '12-task queue, 2 parallel'],
        highlight: false,
        badge: 'Power Users',
      },
    ],
  },

  {
    id: 'suno',
    name: 'Suno',
    provider: 'Suno',
    providerId: 'suno',
    description: 'AI music generator — v5.5 is the flagship model. Credits refresh monthly; commercial rights require a paid plan.',
    category: 'media',
    url: 'https://suno.com/pricing',
    lastVerified: '2026-08-17',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['v4.5-all model', '50 credits/day (10 songs)', 'Non-commercial use only', 'Shared generation queue'],
        highlight: false,
      },
      {
        name: 'Pro',
        monthlyPrice: 10,
        annualMonthlyPrice: 8,
        perSeat: false,
        features: ['2,500 credits/mo (500 songs)', 'v5.5 + all advanced models', 'Commercial use for new songs', 'Stem separation (2 types)', 'Priority queue (10 concurrent)'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Premier',
        monthlyPrice: 30,
        annualMonthlyPrice: 24,
        perSeat: false,
        features: ['10,000 credits/mo (2,000 songs)', 'Suno Studio access', 'Custom-tuned v5.5', 'Stem separation (3 types)'],
        highlight: false,
        badge: 'Best Value',
      },
    ],
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    provider: 'ElevenLabs',
    providerId: 'elevenlabs',
    description: 'AI voice & audio platform — Eleven v3 expressive TTS, Multilingual v2, Music, and Scribe STT. Annual billing is two months free on every tier.',
    category: 'media',
    url: 'https://elevenlabs.io/pricing',
    lastVerified: '2026-08-17',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['10k credits/mo', 'TTS, STT, music & sound FX', '3 Studio projects'],
        highlight: false,
      },
      {
        name: 'Starter',
        monthlyPrice: 6,
        annualMonthlyPrice: 5,
        perSeat: false,
        features: ['30k credits/mo', 'Commercial license', 'Instant voice cloning', '20 Studio projects', 'Dubbing Studio'],
        highlight: false,
      },
      {
        name: 'Creator',
        monthlyPrice: 22,
        annualMonthlyPrice: 18.33,
        perSeat: false,
        features: ['121k credits/mo', 'Professional voice cloning', 'First month 50% off', 'Higher-quality audio'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Pro',
        monthlyPrice: 99,
        annualMonthlyPrice: 82.5,
        perSeat: false,
        features: ['600k credits/mo', '44.1kHz PCM via API', '192 kbps audio'],
        highlight: false,
      },
      {
        name: 'Scale',
        monthlyPrice: 299,
        annualMonthlyPrice: 249.17,
        perSeat: false,
        features: ['1.8M credits/mo', '3 workspace seats included', 'Team collaboration', '3 professional voice clones'],
        highlight: false,
      },
      {
        name: 'Business',
        monthlyPrice: 990,
        annualMonthlyPrice: 825,
        perSeat: false,
        features: ['6M credits/mo', '10 workspace seats', 'Low-latency TTS from 5¢/min', '10 professional voice clones'],
        highlight: false,
        badge: 'Power Users',
      },
      {
        name: 'Enterprise',
        monthlyPrice: null,
        annualMonthlyPrice: null,
        perSeat: true,
        features: ['Custom DPA & SLAs', 'HIPAA BAAs', 'Custom SSO', 'Elevated concurrency'],
        highlight: false,
        badge: 'Contact Sales',
      },
    ],
  },
  {
    id: 'kling',
    name: 'Kling AI',
    provider: 'Kuaishou',
    providerId: 'kling',
    description: 'Kuaishou\'s AI video & image generator on the Kling 3.0 series (Video 3.0/Omni, Image 3.0 Omni). List prices shown — renewals run ~12% lower and annual ~34% off; first-month promos are common.',
    category: 'media',
    url: 'https://kling.ai/app/membership/membership-plan',
    lastVerified: '2026-08-17',
    tiers: [
      {
        name: 'Basic',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Free forever', 'Daily login credits', 'Video 2.6 voice control', 'No commercial use'],
        highlight: false,
      },
      {
        name: 'Standard',
        monthlyPrice: 10,
        annualMonthlyPrice: 6.6,
        perSeat: false,
        features: ['660 credits/mo', 'Commercial use rights', 'Daily free credits for subscribers'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Pro',
        monthlyPrice: 37,
        annualMonthlyPrice: 24.42,
        perSeat: false,
        features: ['3,000 credits/mo', 'As low as $1.09 per 100 credits', 'Queue unlimited tasks'],
        highlight: false,
      },
      {
        name: 'Premier',
        monthlyPrice: 92,
        annualMonthlyPrice: 60.72,
        perSeat: false,
        features: ['8,000 credits/mo', 'Top queue priority', 'Commercial use'],
        highlight: false,
      },
      {
        name: 'Ultra',
        monthlyPrice: 180,
        annualMonthlyPrice: 119.17,
        perSeat: false,
        features: ['26,000 credits/mo', 'Highest throughput', 'New top tier (2026)'],
        highlight: false,
        badge: 'New',
      },
      {
        name: 'Team',
        monthlyPrice: 99,
        annualMonthlyPrice: 59,
        perSeat: true,
        features: ['10,000 credits/seat/mo pooled', 'RBAC & corporate billing', 'Annual billed $708/seat'],
        highlight: false,
      },
    ],
  },
  {
    id: 'runway',
    name: 'Runway',
    provider: 'Runway',
    providerId: 'runway',
    description: 'AI video suite built on Gen-4.5, Aleph 2.0 editing, and Act-Two capture — plus hub access to Kling 3.0, Seedance 2.0 & Veo 3.1. The Unlimited plan was retired for Max in June 2026.',
    category: 'media',
    url: 'https://runwayml.com/pricing',
    lastVerified: '2026-08-17',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['125 one-time credits', 'Gen-4 Turbo & TTS', '3 video projects', '5 GB storage'],
        highlight: false,
      },
      {
        name: 'Standard',
        monthlyPrice: 15,
        annualMonthlyPrice: 12,
        perSeat: false,
        features: ['625 credits/mo', 'All AI models (Gen-4.5, Veo 3.1, Nano Banana Pro)', '4K upscaling', 'No watermarks'],
        highlight: false,
      },
      {
        name: 'Pro',
        monthlyPrice: 35,
        annualMonthlyPrice: 28,
        perSeat: false,
        features: ['2,250 credits/mo', 'Custom voice lip-sync & TTS', '500 GB storage'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Max',
        monthlyPrice: 95,
        annualMonthlyPrice: 76,
        perSeat: false,
        features: ['9,500 credits/mo', '1-month credit rollover', 'First access to newest models', 'Replaced Unlimited (Jun 2026)'],
        highlight: false,
        badge: 'Best Value',
      },
      {
        name: 'Enterprise',
        monthlyPrice: null,
        annualMonthlyPrice: null,
        perSeat: true,
        features: ['Custom credit packages', 'SSO & workspace analytics', 'Configurable teamspaces', 'Priority support'],
        highlight: false,
        badge: 'Contact Sales',
      },
    ],
  },
  {
    id: 'microsoft-copilot',
    name: 'Microsoft Copilot',
    provider: 'Microsoft',
    providerId: 'microsoft',
    description: 'Microsoft\'s AI in Windows, Edge, Bing, and Microsoft 365 apps (Word, Excel, PowerPoint, Teams).',
    category: 'chat',
    url: 'https://www.microsoft.com/en-us/microsoft-365-copilot/pricing',
    lastVerified: '2026-07-11',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Copilot in Bing & Edge', 'Image generation (limited)', 'Basic chat'],
        highlight: false,
      },
      {
        name: 'M365 Premium',
        monthlyPrice: 19.99,
        annualMonthlyPrice: 19.99,
        perSeat: false,
        features: ['Priority access to latest models', 'Copilot in personal M365 apps', 'Full Office apps + up to 6 TB OneDrive', 'Researcher & Analyst agents', 'Copilot Actions'],
        highlight: false,
      },
      {
        name: 'Copilot Business',
        monthlyPrice: 25.2,
        annualMonthlyPrice: 18,
        perSeat: true,
        features: ['$18 promo through Sep 2026', 'M365 Copilot in Teams, Word, Excel', 'Work IQ intelligence layer', 'Admin controls (up to 300 users)', 'Requires M365 Business base plan'],
        highlight: true,
        badge: 'SMB',
      },
      {
        name: 'M365 Copilot',
        monthlyPrice: 30,
        annualMonthlyPrice: 30,
        perSeat: true,
        features: ['Enterprise add-on (E3/E5/Business)', 'Full Copilot across Office apps', 'Latest OpenAI GPT-5.X models', 'Copilot Studio agents', 'Enterprise data protection'],
        highlight: false,
        badge: 'Enterprise',
      },
    ],
  },
];
