import type { Subscription } from './types';

export const SUBSCRIPTIONS: Subscription[] = [
  // ── Chat AI Assistants ──────────────────────────────────────────────────────
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    provider: 'OpenAI',
    providerId: 'openai',
    description: 'The world\'s most popular AI assistant with GPT-4o, web search, and DALL·E 3.',
    category: 'chat',
    url: 'https://openai.com/chatgpt/pricing',
    underlyingModels: ['openai/gpt-4o', 'openai/o3'],
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['GPT-4o (limited)', 'Web search (limited)', 'DALL·E 3 (limited)', 'GPT-4o mini (unlimited)'],
        highlight: false,
      },
      {
        name: 'Plus',
        monthlyPrice: 20,
        annualMonthlyPrice: 20,
        perSeat: false,
        features: ['GPT-4o (5x more)', 'o3-mini reasoning', 'Web search', 'DALL·E 3', 'Advanced data analysis', 'Custom GPTs'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Pro',
        monthlyPrice: 200,
        annualMonthlyPrice: 200,
        perSeat: false,
        features: ['Unlimited GPT-4o', 'o1 Pro mode (more compute)', 'o3', 'Advanced voice', 'Sora video generation'],
        highlight: false,
      },
      {
        name: 'Team',
        monthlyPrice: 30,
        annualMonthlyPrice: 25,
        perSeat: true,
        features: ['Everything in Plus', 'Team workspace', 'Admin console', 'SSO & SAML', 'No training on data'],
        highlight: false,
      },
    ],
  },
  {
    id: 'claude-ai',
    name: 'Claude.ai',
    provider: 'Anthropic',
    providerId: 'anthropic',
    description: 'Anthropic\'s AI assistant with long context, coding, and analysis capabilities.',
    category: 'chat',
    url: 'https://claude.ai/pricing',
    underlyingModels: ['anthropic/claude-sonnet-4-6', 'anthropic/claude-opus-4-6'],
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Claude Sonnet (limited)', 'Basic Projects', '5 messages/day on Opus'],
        highlight: false,
      },
      {
        name: 'Pro',
        monthlyPrice: 20,
        annualMonthlyPrice: 20,
        perSeat: false,
        features: ['Claude Sonnet (5x more)', 'Claude Opus (limited)', 'Projects & Artifacts', 'Priority access'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Max',
        monthlyPrice: 100,
        annualMonthlyPrice: 100,
        perSeat: false,
        features: ['5x more usage than Pro', 'Extended thinking', 'Claude Opus priority', 'Research mode'],
        highlight: false,
      },
      {
        name: 'Team',
        monthlyPrice: 30,
        annualMonthlyPrice: 25,
        perSeat: true,
        features: ['Everything in Pro', 'Team workspace', 'Central billing', 'Longer context sharing'],
        highlight: false,
      },
    ],
  },
  {
    id: 'gemini-advanced',
    name: 'Gemini Advanced',
    provider: 'Google',
    providerId: 'google',
    description: 'Google\'s most capable AI, included with Google One AI Premium. Access to Gemini Ultra.',
    category: 'chat',
    url: 'https://gemini.google.com/about',
    underlyingModels: ['google/gemini-2-5-pro'],
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Gemini 2.0 Flash', 'Basic image generation', 'Google integrations'],
        highlight: false,
      },
      {
        name: 'AI Premium',
        monthlyPrice: 20,
        annualMonthlyPrice: 20,
        perSeat: false,
        features: ['Gemini 2.5 Pro', '2TB Google One storage', 'Deep Research', 'NotebookLM Plus', 'Workspace integration'],
        highlight: true,
        badge: 'Best Value',
      },
    ],
  },
  {
    id: 'grok',
    name: 'Grok',
    provider: 'xAI',
    providerId: 'x-ai',
    description: 'xAI\'s AI with real-time X data access and SuperGrok for advanced reasoning.',
    category: 'chat',
    url: 'https://x.ai/grok',
    underlyingModels: ['x-ai/grok-3'],
    tiers: [
      {
        name: 'X Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['Grok 3 (limited)', 'X posts access'],
        highlight: false,
      },
      {
        name: 'X Premium',
        monthlyPrice: 8,
        annualMonthlyPrice: 7,
        perSeat: false,
        features: ['Grok 3 (more usage)', 'Real-time X data'],
        highlight: false,
      },
      {
        name: 'SuperGrok',
        monthlyPrice: 30,
        annualMonthlyPrice: 22,
        perSeat: false,
        features: ['Grok 3 (unlimited)', 'Deep Search', 'Think mode', 'Imagine (image gen)', 'Big Brain mode'],
        highlight: true,
        badge: 'Most Capable',
      },
    ],
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    provider: 'Perplexity',
    providerId: 'perplexityai',
    description: 'AI-powered answer engine with real-time web search and citations.',
    category: 'search',
    url: 'https://perplexity.ai/pro',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['5 Pro searches/day', 'Unlimited quick searches', 'Web citations'],
        highlight: false,
      },
      {
        name: 'Pro',
        monthlyPrice: 20,
        annualMonthlyPrice: 17,
        perSeat: false,
        features: ['600+ Pro searches/day', 'GPT-4o / Claude 3.5', 'Image generation', 'File uploads', 'API credits ($5/mo)'],
        highlight: true,
        badge: 'Most Popular',
      },
    ],
  },

  // ── Coding Assistants ───────────────────────────────────────────────────────
  {
    id: 'cursor',
    name: 'Cursor',
    provider: 'Cursor',
    providerId: 'cursor',
    description: 'AI-first code editor built on VS Code with deep codebase understanding.',
    category: 'coding',
    url: 'https://cursor.sh/pricing',
    tiers: [
      {
        name: 'Hobby',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['2 weeks Pro trial', '2000 completions/mo', '50 slow premium requests'],
        highlight: false,
      },
      {
        name: 'Pro',
        monthlyPrice: 20,
        annualMonthlyPrice: 16,
        perSeat: false,
        features: ['Unlimited completions', '500 fast premium requests', 'Unlimited slow requests', 'Background agents'],
        highlight: true,
        badge: 'Most Popular',
      },
      {
        name: 'Business',
        monthlyPrice: 40,
        annualMonthlyPrice: 40,
        perSeat: true,
        features: ['Everything in Pro', 'Team billing', 'SSO & SAML', 'Admin dashboard', 'Centralized storage'],
        highlight: false,
      },
    ],
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    provider: 'Microsoft',
    providerId: 'microsoft',
    description: 'AI pair programmer integrated into GitHub and VS Code with multi-model support.',
    category: 'coding',
    url: 'https://github.com/features/copilot',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['2000 completions/mo', '50 chat messages/mo', 'GPT-4o & Claude 3.5'],
        highlight: false,
      },
      {
        name: 'Individual',
        monthlyPrice: 10,
        annualMonthlyPrice: 8.33,
        perSeat: false,
        features: ['Unlimited completions', 'Unlimited chat', 'Multi-model choice', 'CLI assistant'],
        highlight: false,
      },
      {
        name: 'Business',
        monthlyPrice: 19,
        annualMonthlyPrice: 19,
        perSeat: true,
        features: ['Everything in Individual', 'Org-wide policy mgmt', 'Audit logs', 'IP indemnity'],
        highlight: true,
        badge: 'Teams',
      },
      {
        name: 'Enterprise',
        monthlyPrice: 39,
        annualMonthlyPrice: 39,
        perSeat: true,
        features: ['Everything in Business', 'Custom models', 'PR summaries', 'Knowledge bases', 'Fine-tuning'],
        highlight: false,
      },
    ],
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    provider: 'Codeium',
    providerId: 'codeium',
    description: 'Agentic AI code editor (formerly Codeium) with Cascade autonomous coding.',
    category: 'coding',
    url: 'https://windsurf.com/pricing',
    tiers: [
      {
        name: 'Free',
        monthlyPrice: 0,
        annualMonthlyPrice: 0,
        perSeat: false,
        features: ['5 user prompts/day', 'Unlimited completions', 'Cascade (limited)'],
        highlight: false,
      },
      {
        name: 'Pro',
        monthlyPrice: 15,
        annualMonthlyPrice: 12,
        perSeat: false,
        features: ['Unlimited Cascade flows', 'Advanced models (GPT-4o, Claude 3.5)', 'Priority access'],
        highlight: true,
        badge: 'Best Value',
      },
      {
        name: 'Teams',
        monthlyPrice: 30,
        annualMonthlyPrice: 30,
        perSeat: true,
        features: ['Everything in Pro', 'Centralized billing', 'Usage insights', 'SSO'],
        highlight: false,
      },
    ],
  },
  {
    id: 'claude-code',
    name: 'Claude Code',
    provider: 'Anthropic',
    providerId: 'anthropic',
    description: 'Agentic CLI coding tool. Billed against your Anthropic API usage — no flat subscription.',
    category: 'coding',
    url: 'https://claude.ai/code',
    underlyingModels: ['anthropic/claude-sonnet-4-6'],
    tiers: [
      {
        name: 'API Usage',
        monthlyPrice: null,
        annualMonthlyPrice: null,
        perSeat: false,
        features: ['Pay per token (API rates)', 'No subscription fee', 'Claude Sonnet 4.6 default', 'Full autonomous coding'],
        highlight: true,
        badge: 'Usage-Based',
      },
    ],
  },
];
